# This is a basic workflow that is manually triggered

name: Manual workflow
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      message:
        description: 'Commit message'
        # Default value if no value is explicitly provided
        default: 'i18n pointer updated to latest'
        required: true
permissions:
 contents: write
 pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
#        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
          git status
          git branch feature/i18n-update
          git checkout feature/i18n-update
          cd fluxDemo
          git config pull.rebase false
          git pull origin main --allow-unrelated-histories
          cd ..
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -a -m "${{ github.event.inputs.message }}"
          git push -u origin feature/i18n-update

